routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware( 'auth')->name('home');

Route::match(['get', 'post'], '/botman', 'BotManController@handle');
Route::get('/botman/tinker', 'BotManController@tinker');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('admin');
Route::resource('brands','BrandController')->middleware('admin');
Route::resource('categories','CategoryController')->middleware('admin');
Route::resource('products','ProductController')->middleware('admin');
Route::post('import','ProductController@import')->name('import')->middleware('admin');
Route::post('brand.import','BrandController@import')->name('brand.import')->middleware('admin');

Route::post('category.import','CategoryController@import')->name('category.import')->middleware('admin');

Route::get('myanmar_idol', function (){
   return view('myanmaridol');
});

Route::get('image', 'GetImgaeController@getimage');


Route::get('rate', 'RangeController@index')->name('range.index');
Route::post('rate/edit', 'RangeController@edit')->name('range.edit');

Route::post('rate', 'RangeController@store')->name('range.store');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name','model','price','range','qty','description','category_id','brand_id'];
    public function categories()
    {
        return $this->belongsTo('App\Models\Category','category_id');
    }

    public function brands()
    {
        return $this->belongsTo('App\Models\Brand','brand_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Product;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use DB;


class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   $categories=Category::get();
        $brands=Brand::get();
        $products=Product::with('categories','brands')->get();

        return view('product.index', ['products' => $products]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::get();
        $brands=Brand::get();
        return view('product.create',compact('categories','brands'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

         $product =new Product();
        $product->name=$request->input('product_name');
        $product->model=$request->input('model');
        $product->price_mmk=$request->input('price_mmk');
        $product->price_usd=$request->input('price_usd');
        $product->qty=$request->input('qty');
        $product->description=$request->input('description');
        $product->category_id=$request->input('category_name');
        $product->brand_id=$request->input('brand_name');
        $product->save();
        return redirect("products");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
        $categories=Category::get();
        $brands=Brand::get();
        $product=Product::with('categories','brands')
        ->where('id',$id)
        ->first();
        return view('product.show')->with('product',$product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {  
        $product=Product::where('id',$id)->first();
        $categories=Category::all();
        $brands=Brand::all();


        return view('product.edit',compact('brands','categories', 'product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
     $data = [
            'name'       => $request->get('name'),
            'model'       => $request->get('model'),
            'price_mmk'=> $request->get('price_mmk'),
            'price_usd'=> $request->get('price_usd'),
            'qty'      => $request->get('qty'),
            'description'      => $request->get('description'),
            'category_id'  => $request->get('category_name'),
            'brand_id'  => $request->get('brand_name')

        ];

        $product = Product::find($id);
        $product->price_mmk = $request->price_mmk;
       $product->price_usd = $request->price_usd;
        $product->update($data);
        $product->save();
        return redirect('products')->with('update','Product is successfully Updated');
    }

    public function import(Request $request)
    {
      $file = $request->file('file');      
      $filename = $file->getClientOriginalName();
      $extension = $file->getClientOriginalExtension();
      $tempPath = $file->getRealPath();
      $fileSize = $file->getSize();
      $mimeType = $file->getMimeType();
      $location = 'uploads';
      $file->move($location,$filename);
      $filepath = public_path($location."/".$filename);
      $file = fopen($filepath,"r");
      $importData_arr = array();
      $i = 0;
        

while (($filedata = fgetcsv($file, 1000, ",")) !== FALSE) {
             $num = count($filedata );
             
             // Skip first row (Remove below comment if you want to skip the first row)
             if($i == 0){
                $i++;
                continue; 
             }
             for ($c=0; $c < $num; $c++) {
                $importData_arr[$i][] = $filedata [$c];
             }
             $i++;
          }
          fclose($file);



           foreach($importData_arr as $importData){

                if($importData[6]=='-' || $importData[6] == '')
                {
                  $brand= DB::table('brands')
                           ->select('id')
                           ->where('name','nth')
                           ->first();
                $brand_id=$brand->id;
                }
                else  {
                    $brand= DB::table('brands')
                           ->select('id')
                           ->where('name',$importData[6])
                           ->first();
                    if(!isset($brand))
                    {
                       return response()->json(['statust'=> $importData[6]. ' does not exit in Brand List']);
                    }
                $brand_id=$brand->id;
                }

                if($importData[7]=='-' || $importData[7] == '')
                {
                $category= DB::table('categories')
                           ->select('id')
                           ->where('name','Nth')
                           ->first();
                $category_id=$category->id;
                }
                else {
                    $category= DB::table('categories')
                           ->select('id')
                           ->where('name',$importData[7])
                           ->first();
                    if(!isset($category))
                    {
                        return response()->json(['statust'=> $importData[7]. ' does not exit in Category List']);
                    }
                    $category_id=$category->id;
                }

                $product=new Product();
                $product->name=$importData[1];
                $product->model=$importData[0];
                $product->price_mmk=$importData[2];
                $product->price_usd=$importData[3];
                $product->qty=$importData[4];
                $product->description=$importData[5];
                $product->category_id=$category_id;
                $product->brand_id=$brand_id;
                $product->save();

            // $insertData = array(
            //    "name"=>$importData[1],
            //    "model"=>$importData[0],
            //    "price_mmk"=>$importData[2],
            //     "price_usd"=>$importData[3],
            //      "qty"=>$importData[4],
            //    "description"=>$importData[5],
            //    "category_id"=>$category_id,
            //     "brand_id"=>$brand_id);
            // Product::create($insertData);

          }
         

    // Redirect to index
        return redirect("products")->with('products','Products are successfully imported');
  
}


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
              $product->delete();
                return redirect('products')->with('delete','Product is successfully Deleted');
    }
}

resources/views/product/create.blade.php
@extends('layouts.backend')

@section('content')
<div class="container">
	 <div class="row">
    <div class="col-md-3">
     
    </div>
    <div class="col-md-6">
    
<br>
<br>
        	 <h3><b>Add New Product</b></h3>
        	 <br>

<form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                
                <div class="uk-width-medium-1-2">
                    <div class="uk-form-row">
                        <div class="uk-form-row">
                            <label for="title">Product Name</label>
                            <input id="title" type="text" name="product_name" class="form-control" value="{{ old('product_name') }}" autofocus  />
                        </div>
                      </div>
                      
                        
                    </div>
                     <div class="uk-width-medium-1-2">
                    <div class="uk-form-row">
                        <div class="uk-form-row">
                            <label for="title">Product Model</label>
                            <input id="title" type="text" name="model" class="form-control" value="{{ old('model') }}" autofocus  />
                        </div>
                      </div>
                      
                        
                    </div>
                     <div class="uk-width-medium-1-2">
                        <div class="uk-form-row">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="uk-form-row">
                                        <label for="title">Price in MMK</label>
                                        <input id="title" type="text" name="price_mmk" class="form-control" value="{{ old('price_mmk') }}" autofocus  />
                                    </div>
                                </div>
                                 <div class="col-md-4">
                                     <div class="uk-form-row">
                                            <label for="title"> Price in USD </label>
                                            <input id="title" type="text" name="price_usd" class="form-control" value="{{ old('price_usd') }}" autofocus  />
                                        </div>
                                 </div>
                                 <div class="col-md-4">
                                    <div class="uk-form-row">
                                        <label for="title"> Qty</label>
                                        <input id="title" type="text" name="qty" class="form-control" value="{{ old('price') }}" autofocus  />
                                    </div>
                                </div>
                            </div>
                        
                      </div>
                      
                        
                    </div>
                     <div class="uk-width-medium-1-2">
                    <div class="uk-form-row">
                        <div class="uk-form-row">
                            <label for="title">Product Description</label>
                            <input id="title" type="textarea" name="description" class="form-control" value="{{ old('description') }}" autofocus  />
                        </div>
                      </div>
                      
                        
                    </div>
                    <div class="uk-form-row">
                            <label for="title">Select Category</label>
                            <select name="category_name" class="form-control">                          
                                @foreach($categories as $category)
                                <option value="{{$category->id}}">
                                {{$category->name}} 
                                </option>
                                @endforeach
                            </select>
                           
                        </div>
                        <div class="uk-form-row">
                            <label for="title">Select Brand</label>
                            <select name="brand_name" class="form-control">                          
                                @foreach($brands as $brand)
                                <option value="{{$brand->id}}">
                                {{$brand->name}} 
                                </option>
                                @endforeach
                            </select>
                           
                        </div>
<br>
                    <div class="uk-form-row">
                       <input type="submit" class="btn btn-success" value="Create">
                      
                    </div>
                </div>
            </form>    </div>
    <div class="col-md-3">
    
    </div>
  </div>
</div>

@endsection

resources/views/product/edit.blade.php
@extends('layouts.backend')

@section('content')
<div class="container">
	 <div class="row">
    <div class="col-md-3">
     
    </div>
    <div class="col-md-6">
    
<br>
<br>
        	 <h3><b>Edit Product</b></h3>
        	 <br>

{!! Form::model($product, ['route' => ['products.update', $product->id], 'method' => 'patch','files' => true]) !!}
                {{ csrf_field() }}
                
                <div class="uk-width-medium-1-2">
                    <div class="uk-form-row">
                        <div class="uk-form-row">
                            <label for="title">Product Name</label>
                            <input id="title" type="text" name="name" class="form-control" value="{{ $product->name }}" autofocus  />
                        </div>
                      </div>
                      
                        
                    </div>
                     <div class="uk-width-medium-1-2">
                    <div class="uk-form-row">
                        <div class="uk-form-row">
                            <label for="title">Product Model</label>
                            <input id="title" type="text" name="model" class="form-control" value="{{ $product->model }}" autofocus  />
                        </div>
                      </div>
                      
                        
                    </div>
                     <div class="uk-width-medium-1-2">
                        <div class="uk-form-row">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="uk-form-row">
                                        <label for="title">Product Price in MMK</label>
                                        <input id="title" type="text" name="price_mmk" class="form-control" value="{{ $product->price_mmk}}" autofocus  />
                                    </div>
                                </div>
                                 <div class="col-md-4">
                                     <div class="uk-form-row">
                                            <label for="title"> Product Price in USD </label>
                                            <input id="title" type="text" name="price_usd" class="form-control" value="{{ $product->price_usd }}" autofocus  />
                                        </div>
                                 </div>
                                 <div class="col-md-4">
                                    <div class="uk-form-row">
                                        <label for="title"> Qty</label>
                                        <input id="title" type="text" name="qty" class="form-control" value="{{ $product->qty }}" autofocus  />
                                    </div>
                                </div>
                            </div>
                        
                      </div>
                      
                        
                    </div>
                     <div class="uk-width-medium-1-2">
                    <div class="uk-form-row">
                        <div class="uk-form-row">
                            <label for="title">Product Description</label>
                            <input id="title" type="textarea" name="description" class="form-control" value="{{ $product->description }}" autofocus  />
                        </div>
                      </div>
                      
                        
                    </div>
                    <div class="uk-form-row">
                            <label for="title">Select Category</label>
                        {!! Form::select('category_name', $categories->pluck('name','id'), $product->category_id, ['class'=>'form-control']) !!}
                        </div>
                        <div class="uk-form-row">
                            <label for="title">Select Brand</label>

                            {!!  Form::select('brand_name', $brands->pluck('name','id'), $product->brand_id, ['class'=>'form-control']) !!}
                           
                        </div>
<br>

                    <div class="uk-form-row">
                       <input type="submit" class="btn btn-success" value="Update">
                      
                    </div>
                </div>
                        {!! Form::close() !!}
  </div>
    <div class="col-md-3">
    
    </div>
  </div>
</div>

@endsection

resources/views/product/index.blade.php
@extends('layouts.backend')

@section('content')




 <div class="content">
        <div class="container-fluid">
            <div class="navbar-wrapper">
                {{--<a  class="btn btn-info" href="{!! route('brands.index') !!}" >Back</a>--}}
                <a  class="btn btn-success" href="{!! route('products.create') !!}" >Create</a>
            </div>
          @if (session('products'))
                        <div class="alert alert-success">
                            {{ session('products') }}
                        </div>
                    @endif
              @if (session('update'))
                  <div class="alert alert-success">
                      {{ session('update') }}
                  </div>
              @endif
          <div class="row">
  <div class="col-md-12">

 <form action="{{ route('import') }}" method="post" enctype="multipart/form-data" >
                @csrf
               <div class="row">
                 <div class="col-md-3"><input type="file" name="file" class="form-control" required></div>
                 <div class="col-md-2"><button type="submit" class="btn btn-primary pull-right">Import Excel
                  </button> 
                 </div>
               </div>
             </form>
              <div class="card">
                <div class="card-header card-header-primary">
                  
                  <h4 class="card-title ">Product Name</h4>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                           <table id="myTable" class="display">
                      <thead class=" text-primary">
                        <th>
                          ID
                        </th>
                        <th>
                          Name
                        </th>
                         <th>
                          Model
                        </th>
                         <th>
                          Price in MMK
                        </th>
                         <th>
                          Price in USD
                        </th>
                         <th>
                          QTY
                        </th>
                         <th>
                          Description
                        </th>
                        <th>
                         Category
                        </th>
                        <th>
                         Brand
                        </th>
                        <th>
                         Action
                        </th>
                        
                      </thead>
                      <tbody>


                        @foreach ($products  as $product)
                        <tr>
                        	<td>
                            {{$product->id}}
                          </td>
                          <td>
                          {{$product->name}}
                          </td>
                           <td>
                           {{$product->model}}
                          </td>
                           <td>
                           {{$product->price_mmk}}
                          </td>
                           <td>
                           {{$product->price_usd}}
                          </td>
                           <td>
                           {{$product->qty}}
                          </td>
                           <td>
                           {{$product->description}}
                          </td>
                           <td>
                           {{$product->categories['name']}}
                          </td>
                           <td>
                           {{$product->brands['name']}}
                          </td>


                          <td>
                            {!! Form::open(['route' => ['products.destroy', $product->id], 'method' => 'delete']) !!}
                            <a href="{!! route('products.show', [$product->id]) !!}"><i class="material-icons">
                                  visibility
                                  </i></a>
                              <a href="{!! route('products.edit', [$product->id]) !!}"><i class="material-icons">
                                  create
                                  </i></a>
                            
                            {!! Form::button('<i class="material-icons">
                              delete_outline
                              </i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                          </td>
                          
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="card card-plain">
               
               
              </div>
            </div>
          </div>
        </div>
      </div>


@endsection

resources/views/product/show.blade.php
@extends('layouts.backend')

@section('content')
    <div class="container">

        <br>
        <br>
        <h3><b>View Brand</b></h3>
        <br>



            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Category</th>
                    <th scope="col">Brand</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->categories->name }}</td>
                    <td>{{ $product->brands->name }}</td>
                </tr>
                </tbody>
            </table>

        </div>


@endsection