routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware( 'auth')->name('home');

Route::match(['get', 'post'], '/botman', 'BotManController@handle');
Route::get('/botman/tinker', 'BotManController@tinker');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('admin');
Route::resource('brands','BrandController')->middleware('admin');
Route::resource('categories','CategoryController')->middleware('admin');
Route::resource('products','ProductController')->middleware('admin');
Route::post('import','ProductController@import')->name('import')->middleware('admin');
Route::post('brand.import','BrandController@import')->name('brand.import')->middleware('admin');

Route::post('category.import','CategoryController@import')->name('category.import')->middleware('admin');

Route::get('myanmar_idol', function (){
   return view('myanmaridol');
});

Route::get('image', 'GetImgaeController@getimage');


Route::get('rate', 'RangeController@index')->name('range.index');
Route::post('rate/edit', 'RangeController@edit')->name('range.edit');

Route::post('rate', 'RangeController@store')->name('range.store');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];

    public function brands(){
        return $this->belongsToMany('App\Models\Brand','category_brand');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;
use App\Models\Category;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $categories=Category::get();

        return view('category.index')->with('categories', $categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create'); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category =new Category();
        $category->name=$request->input('category_name');
        $category->csort=$request->input('csort');

        $category->save();
        return redirect("categories");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category=Category::where('id',$id)->first();
        return view('category.show')->with('category',$category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories=Category::where('id',$id)->first();
        return view('category.edit')->with('categories',$categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $category = Category::find($id);
       $category->name = $request->category_name;
       $category->csort = $request->csort;

       $category->save();
       return redirect('categories')->with('update','Category is successfully Updated');
    }


    public function import(Request $request)
    {
      $file = $request->file('file');

      // File Details 
      $filename = $file->getClientOriginalName();
      $extension = $file->getClientOriginalExtension();
      $tempPath = $file->getRealPath();
      $fileSize = $file->getSize();
      $mimeType = $file->getMimeType();

        $location = 'uploads';

          // Upload file
          $file->move($location,$filename);

          // Import CSV to Database
          $filepath = public_path($location."/".$filename);


           $file = fopen($filepath,"r");

          $importData_arr = array();
          $i = 0;

           while (($filedata = fgetcsv($file, 1000, ",")) !== FALSE) {
             $num = count($filedata );
             
             if($i == 0){
                $i++;
                continue; 
             }
             for ($c=0; $c < $num; $c++) {
                $importData_arr[$i][] = $filedata [$c];
             }
             $i++;
          }
          fclose($file);



           foreach($importData_arr as $importData){

           $category =new Category();
                $category->name=$importData[1];
                $category->csort=$importData[4];
                $category->save();

          }

        return redirect("categories")->with('categories','Categories are successfully imported');

 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
              $category = Category::find($id);
              $category->delete();
            return redirect('categories')->with('delete','Category is successfully Deleted');

        
        
    }
}

resources/views/category/create.blade.php
@extends('layouts.backend')

@section('content')

<div class="container">
	 <div class="row">
    <div class="col-md-3">
     
    </div>
    <div class="col-md-6">
    
<br>
<br>
        	 <h3><b>Add New Category</b></h3>
        	 <br>

<form action="{{ route('categories.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                
                <div class="uk-width-medium-1-2">
                    <div class="uk-form-row">
                        <div class="uk-form-row">
                            <label for="title">Category Name</label>
                            <input id="title" type="text" name="category_name" class="form-control" value="{{ old('category_name') }}" autofocus  />
                        </div>
                        <div class="uk-form-row">
                            <label for="title">Category Priority</label>
                            <input id="title" type="text" name="csort" class="form-control" value="{{ old('csort') }}" autofocus  />
                        </div>
                      </div>
                      
                        
                    </div>
<br>
                    <div class="uk-form-row">
                       <input type="submit" class="btn btn-success" value="Create">
                      
                    </div>
                </div>
            </form>    </div>
    <div class="col-md-3">
    
    </div>
  </div>
</div>

@endsection

resources/views/category/edit.blade.php
@extends('layouts.backend')

@section('content')

<div class="container">
	<div class="row">
    <div class="col-md-3">
     
    </div>
    <div class="col-md-6">
    
<br>
<br>
        	 <h3><b>Edit  Category</b></h3>
        	 <br>



{!! Form::model($categories, ['route' => ['categories.update', $categories->id], 'method' => 'patch','files' => true]) !!}

<div class="uk-width-medium-1-2">
                    <div class="uk-form-row">
                        <div class="uk-form-row">
                            <label for="title">Category Name</label>
                            <input id="title" type="text" name="category_name" class="form-control" value="{{ $categories->name }}" autofocus  />
                        </div>
                        <div class="uk-form-row">
                            <label for="title">Category Priority</label>
                            <input id="title" type="text" name="csort" class="form-control" value="{{ $categories->csort }}" autofocus  />
                        </div>
                      </div>
                      
                        
                    </div>
<br>
                    <div class="uk-form-row">
                       <input type="submit" class="btn btn-success" value="Edit">
                      
                    </div>
                </div>
            {!! Form::close() !!}
    </div>
    <div class="col-md-3">
    
    </div>
  </div>
</div>

@endsection

resources/views/category/index.blade.php
@extends('layouts.backend')

@section('content')

 <div class="content">
        <div class="container-fluid">
            <div class="navbar-wrapper">
                {{--<a  class="btn btn-info" href="{!! route('brands.index') !!}" >Back</a>--}}
                <a  class="btn btn-success" href="{!! route('categories.create') !!}" >Create</a>
            </div>
                    @if (session('categories'))
                        <div class="alert alert-success">
                            {{ session('categories') }}
                        </div>
                    @endif
                     @if (session('update'))
                        <div class="alert alert-success">
                            {{ session('update') }}
                        </div>
                    @endif
                     @if (session('delete'))
                        <div class="alert alert-success">
                            {{ session('delete') }}
                        </div>
                    @endif
          <div class="row">
            <div class="col-md-12">
               <form action="{{ route('category.import') }}" method="post" enctype="multipart/form-data" >
                @csrf
               <div class="row">
                 <div class="col-md-3"><input type="file" name="file" class="form-control" required></div>
                 <div class="col-md-2"><button type="submit" class="btn btn-primary pull-right">Import Excel
                  </button> 
                 </div>
               </div>
             </form>

              <div class="card">
               
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Categories</h4>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                           <table id="myTable" class="display">
                      <thead class=" text-primary">
                        <th>
                          ID
                        </th>
                        <th>
                          Name
                        </th>
                        <th>
                          Priority
                        </th>
                        <th>
                         Action
                        </th>
                        
                      </thead>
                      <tbody>
                      	@foreach ($categories  as $category)
                        <tr>
                        	<td>
                            {{$category->id}}
                          </td>
                          <td>
                            {{$category->name}}
                          </td>
                          <td>
                            {{$category->csort}}
                          </td>
                          <td>
                             <div>
                            {!! Form::open(['route' => ['categories.destroy', $category->id], 'method' => 'delete']) !!}
                            <a href="{!! route('categories.show', [$category->id]) !!}"><i class="material-icons">
                                  visibility
                                  </i></a>
                              <a href="{!! route('categories.edit', [$category->id]) !!}"><i class="material-icons">
                                  create
                                  </i></a>


                            {!! Form::button('<i class="material-icons">
                              delete_outline
                              </i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure? Products of this category will automatically delete!')"]) !!}
                              {!! Form::close() !!}
                          </td>

                          
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="card card-plain">
               
               
              </div>
            </div>
          </div>
        </div>
      </div>


@endsection

resources/views/category/show.blade.php
@extends('layouts.backend')

@section('content')
<div class="container">
	
<br>
<br>
        	 <h3><b>View  Category</b></h3>
        	 <br>


<div class="row">
	<div class="col-md-2">Name :</div>
	<div class="col-md-6">{{$category->name}}</div>
</div>


    </div>
    
  </div>
</div>

 

@endsection