routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->middleware( 'auth')->name('home');

Route::match(['get', 'post'], '/botman', 'BotManController@handle');
Route::get('/botman/tinker', 'BotManController@tinker');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('admin');
Route::resource('brands','BrandController')->middleware('admin');
Route::resource('categories','CategoryController')->middleware('admin');
Route::resource('products','ProductController')->middleware('admin');
Route::post('import','ProductController@import')->name('import')->middleware('admin');
Route::post('brand.import','BrandController@import')->name('brand.import')->middleware('admin');

Route::post('category.import','CategoryController@import')->name('category.import')->middleware('admin');

Route::get('myanmar_idol', function (){
   return view('myanmaridol');
});

Route::get('image', 'GetImgaeController@getimage');


Route::get('rate', 'RangeController@index')->name('range.index');
Route::post('rate/edit', 'RangeController@edit')->name('range.edit');

Route::post('rate', 'RangeController@store')->name('range.store');

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    protected $fillable = ['name','category_id'];

    public function categories(){
        return $this->belongsToMany('App\Models\Category', 'category_brand');
    }
}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Brand;
use App\Models\Category;
use DB;


class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

       $brands=Brand::get();

        return view('brand.index')->with('brands', $brands);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    { 
        return view('brand.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $brand =new Brand();
        $brand->name=$request->input('brand_name');
        $brand->sort=$request->input('sort');
        $brand->save();
        return redirect("brands");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $brand=Brand::where('id',$id)->first();
        return view('brand.show')->with('brand',$brand);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $brands=Brand::where('id',$id)->first();
        return view('brand.edit')->with('brands',$brands);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $brand = Brand::find($id);

        $brand->name = $request->brand_name;
        $brand->sort = $request->sort;


        $brand->save();

        return redirect('brands')->with('update','Brand is successfully Updated');
    }
    public function import(Request $request)
    {
    $file = $request->file('file');

      // File Details 
      $filename = $file->getClientOriginalName();
      $extension = $file->getClientOriginalExtension();
      $tempPath = $file->getRealPath();
      $fileSize = $file->getSize();
      $mimeType = $file->getMimeType();
      $location = 'uploads';

          // Upload file
          $file->move($location,$filename);

          // Import CSV to Database
          $filepath = public_path($location."/".$filename);


           $file = fopen($filepath,"r");

          $importData_arr = array();
          $i = 0;

           while (($filedata = fgetcsv($file, 1000, ",")) !== FALSE) {
             $num = count($filedata );
             
             if($i == 0){
                $i++;
                continue; 
             }
             for ($c=0; $c < $num; $c++) {
                $importData_arr[$i][] = $filedata [$c];
             }
             $i++;
          }
          fclose($file);


           foreach($importData_arr as $importData){   

                $brand =new Brand();
                $brand->name=$importData[1];
                $brand->sort=$importData[4];
                $brand->save();
          }

    return redirect("brands")->with('brands','Brands are successfully imported');
 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       
              $brand = Brand::find($id);
              $brand->delete();
                return redirect('brands')->with('delete','Brand is successfully Deleted');
    }
}

resources/views/brand/create.blade.php
@extends('layouts.backend')

@section('content')

<div class="container">
	 <div class="row">
    <div class="col-md-3">
     
    </div>
    <div class="col-md-6">
    
<br>
<br>
        	 <h3><b>Add New Brand</b></h3>
        	 <br>

<form action="{{ route('brands.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                
                <div class="uk-width-medium-1-2">
                    <div class="uk-form-row">
                        <div class="uk-form-row">
                            <label for="title">Brand Name</label>
                            <input id="title" type="text" name="brand_name" class="form-control" value="{{ old('brand_name') }}" autofocus  />
                        </div>
                        <div class="uk-form-row">
                        <div class="uk-form-row">
                            <label for="title">Brand Priority</label>
                            <input id="title" type="text" name="sort" class="form-control" value="{{ old('sort') }}" autofocus  />
                        </div>
                      </div>
                      
                        
                    </div>
                     <div class="uk-width-medium-1-2">
                    <div class="uk-form-row">
                        
                      </div>
                      
                        
                    </div>
<br>
                    <div class="uk-form-row">
                       <input type="submit" class="btn btn-success" value="Create">
                      
                    </div>
                </div>
            </form>    </div>
    <div class="col-md-3">
    
    </div>
  </div>
</div>

@endsection

resources/views/brand/edit.blade.php
@extends('layouts.backend')

@section('content')

<div class="container">
	<div class="row">
    <div class="col-md-3">
     
    </div>
    <div class="col-md-6">
    
<br>
<br>
        	 <h3><b>Edit  Brand</b></h3>
        	 <br>



{!! Form::model($brands, ['route' => ['brands.update', $brands->id], 'method' => 'patch','files' => true]) !!}

<div class="uk-width-medium-1-2">
                    <div class="uk-form-row">
                        <div class="uk-form-row">
                            <label for="title">Brand Name</label>
                            <input id="title" type="text" name="brand_name" class="form-control" value="{{ $brands->name }}" autofocus  />
                        </div>
                        <div class="uk-form-row">
                            <label for="title">Brand Priority</label>
                            <input id="title" type="text" name="sort" class="form-control" value="{{ $brands->sort }}" autofocus  />
                        </div>
                      </div>
                      
                        
                    </div>
<br>
                    <div class="uk-form-row">
                       <input type="submit" class="btn btn-success" value="Edit">
                      
                    </div>
                </div>
            {!! Form::close() !!}
    </div>
    <div class="col-md-3">
    
    </div>
  </div>
</div>

@endsection

resources/views/brand/index.blade.php
@extends('layouts.backend')

@section('content')


 <div class="content">

        <div class="container-fluid">
            <div class="navbar-wrapper">
                {{--<a  class="btn btn-info" href="{!! route('brands.index') !!}" >Back</a>--}}
                <a  class="btn btn-success" href="{!! route('brands.create') !!}" >Create</a>
            </div>
           @if (session('brands'))
                        <div class="alert alert-success">
                            {{ session('brands') }}
                        </div>
            @endif
            @if (session('update'))
                        <div class="alert alert-success">
                            {{ session('update') }}
                        </div>
            @endif
            @if (session('delete'))
                        <div class="alert alert-success">
                            {{ session('delete') }}
                        </div>
            @endif
          <div class="row">
            <div class="col-md-12">
               <form action="{{ route('brand.import') }}" method="post" enctype="multipart/form-data">
                @csrf
              <div class="col-md-12">               
                <div class="row">
                  <div class="col-md-3"><input type="file" name="file" class="form-control" required ></div>
                  <div class="col-md-2"><button type="submit" class="btn btn-primary pull-right">Import Excel
                    </button> 
                </div>
              </div>
            </form>
              <div class="card">
                
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Brand Name</h4>
                </div>
                <div class="card-body">
                           <table id="myTable" class="display">
                      <thead class=" text-primary">
                        <th>
                          ID
                        </th>
                        <th>
                          Name
                        </th>
                        <th>
                          Priority
                        </th>
                        <th>
                         Action
                        </th>
                        
                      </thead>
                      <tbody>
                      	@foreach ($brands  as $brand)
                        <tr>
                        	<td>
                            {{$brand->id}}
                          </td>
                          <td>
                            {{$brand->name}}
                          </td>
                           <td>
                            {{$brand->sort}}
                          </td>
                          <td>
                            {!! Form::open(['route' => ['brands.destroy', $brand->id], 'method' => 'delete']) !!}
                            <a href="{!! route('brands.show', [$brand->id]) !!}"><i class="material-icons">
                                  visibility
                                  </i></a>
                              <a href="{!! route('brands.edit', [$brand->id]) !!}"><i class="material-icons">
                                  create
                                  </i></a>
                            

                            {!! Form::button('<i class="material-icons">
                              delete_outline
                              </i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                              {!! Form::close() !!}
                          </td>
                          
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-12">
              <div class="card card-plain">
               
               
              </div>
            </div>
          </div>
        </div>
      </div>



@endsection

resources/views/brand/show.blade.php
@extends('layouts.backend')

@section('content')
<div class="container">
	
<br>
<br>
        	 <h3><b>View  Brand</b></h3>
        	 <br>


<div class="row">
	<div class="col-md-2">Name :</div>
	<div class="col-md-6">{{$brand->name}}</div>
</div>


    </div>
    
  </div>
</div>

 

@endsection